### ISSUE TITLE
Issue with loading mondo Disease ontology

### ISSUE THREAD

**Issue by sunnyosun** [laminlabs/bionty-base#235] opened 2023-03-07 06:01 UTC
I ran into the same error when trying to load mondo (both versions):

<img width="982" alt="Screenshot 2023-03-07 at 12 49 05" src="https://user-images.githubusercontent.com/38218185/223333983-82388c7f-da56-491c-bf2c-70ff680902b2.png">

**Comment by Zethson** [comment] 2023-03-07 11:16
I cannot reproduce this.

**Comment by Zethson** [comment] 2023-03-21 14:03
Closing for now until someone reproduces this

**Comment by sunnyosun** [comment] 2023-04-23 05:43
From @falexwolf :
<img width="841" alt="Screenshot 2023-04-23 at 13 42 59" src="https://user-images.githubusercontent.com/38218185/233821942-78bbd04e-f12d-4d15-af3c-4e7ffe324e2d.png">

**Comment by sunnyosun** [comment] 2023-04-23 06:04
OK, this error seems to be handled as a warning in `pronto==2.5.4`. (I was using 2.5.0 before)

<img width="1057" alt="Screenshot 2023-04-23 at 14 04 13" src="https://user-images.githubusercontent.com/38218185/233822697-269862b6-178a-47c9-91d1-c38d1fcfac9a.png">

I'm going to add a lower bound for pronto version! https://github.com/laminlabs/bionty/pull/312

**Comment by sunnyosun** [comment] 2023-04-23 06:35
> From @falexwolf : <img alt="Screenshot 2023-04-23 at 13 42 59" width="841" src="https://user-images.githubusercontent.com/38218185/233821942-78bbd04e-f12d-4d15-af3c-4e7ffe324e2d.png">

Fixed in https://github.com/laminlabs/bionty/pull/313

**Closed as completed** 2023-04-23 06:35 UTC
